version: '3.7'

services:
  web:
    image: nginx:alpine
    container_name: udemy-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8090:80
    networks:
      - app1_net
      - app2_net

  app1:
    image: httpd:latest
    container_name: udemy-app1
    networks:
      - app1_net

  app2:
    image: httpd:latest
    container_name: udemy-app2
    networks:
      - app2_net

networks:
  app1_net:
  app2_net:
